/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * APruebas.java
 *
 * Created on 14/10/2010, 02:59:48 PM
 */

package conta;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ANGEL
 */
public class APruebas extends javax.swing.JDialog {
    Connection connj;
    ResultSet rs0=null;
    ////****eliminar para el control maestro*******////////
    Connection concontrol=null;
    SimpleDateFormat fechainsertar = new SimpleDateFormat("yyyy/MM/dd");

    /** Creates new form APruebas */
    public APruebas(java.awt.Frame parent, boolean modal,Connection conn) {
        super(parent, modal);
        initComponents();
        connj=conn;
        conexioncontrolmaestro();
    }
    public void salir(){
        if(connj!=null){
            connj=null;
            System.out.println("Conexion en null...............");
        }
        if(concontrol!=null){       ////****eliminar para el control maestro*******////////
            concontrol=null;
            System.out.println("No se pudo cerrar la conexion:\n");
        }

        dispose();
        this.setVisible(false);
    }
    public void conexioncontrolmaestro(){       ////****eliminar para el control maestro*******////////
        if(concontrol!=null){

        }else{
            concontrol=conexion.abrirconexioncontrol();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(conta.CONTAApp.class).getContext().getResourceMap(APruebas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton2)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String clavec=JOptionPane.showInputDialog(this,"clave de cliente");

           /* int respuesta=JOptionPane.showConfirmDialog(this,"Tranferencia de maquinas!!"," I N F O R M A C I O N !!!!!", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                rs0=null;
                try{
                    String senSQL="SELECT * FROM Articulos WHERE [Cliente]='"+clavec+"'";
                    rs0=conexion.consulta(senSQL,concontrol);
                    while(rs0.next()){

                        String claveart=rs0.getString("Clave Articulo");
                        String m1=""+rs0.getString("Maquina 1");
                        String m2=""+rs0.getString("Maquina 2");
                        String m3=""+rs0.getString("Maquina 3");

                        for(int i=1;i<4;i++){
                            if(i==2)
                                m1=m2;
                            if(i==3)
                                m1=m3;

                            m1=m1.toUpperCase();
                            if(m1.equals("CR2")){
                                String senSQLmaquinac="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'CORR', '10', '80');";
                                conexion.modificamov(senSQLmaquinac,connj);
                            }

                            if(m1.equals("TD")||m1.equals("TCY")||m1.equals("DT")||m1.equals("DTE")||m1.equals("STE")||m1.equals("DTF")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'TCY', '25', '85');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("S&S")||m1.equals("DMF")||m1.equals("D&F")||m1.equals("D&")||m1.equals("SDM")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'S&S', '30', '55');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("COM")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'COM', '25', '80');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("SG")||m1.equals("S10")||m1.equals("SD")||m1.equals("SDM")||m1.equals("DTF")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'SUAP', '5', '25');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("S09")||m1.equals("CRD")||m1.equals("CDM")||m1.equals("CDE")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'DIEC', '20', '45');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("CRD")||m1.equals("R04")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'RAY', '15', '50');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("SG")||m1.equals("DG")||m1.equals("G12")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'ENG', '20', '15');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("EMB")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'EMB', '15', '40');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("TD")||m1.equals("DMO")||m1.equals("DMF")||m1.equals("DM")||m1.equals("DG")||m1.equals("D&F")||m1.equals("DT")||m1.equals("CRD")||m1.equals("CDM")||m1.equals("D&")||m1.equals("DTE")||m1.equals("CDE")||m1.equals("SD")||m1.equals("SDM")||m1.equals("DTF")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'DES', '0', '50');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("DMF")||m1.equals("DM")||m1.equals("D&F")||m1.equals("CDM")||m1.equals("SDM")||m1.equals("DTF")||m1.equals("MAN")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'MAN', '0', '50');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }
                            if(m1.equals("DTE")||m1.equals("CDE")||m1.equals("PDO")||m1.equals("STE")){
                                String senSQLmaquina="INSERT INTO articulos_maquinas(clavearticulo, clave, arreglo, velocidad) VALUES ('"+claveart+"', 'PDO', '10', '1');";
                                conexion.modificamov(senSQLmaquina,connj);
                            }

                        }
                        System.err.println("Articulo:  "+claveart);
                    }

                    if(rs0!=null) {
                        rs0.close();
                    }
                } catch (SQLException ex) {JOptionPane.showMessageDialog(null,"ERROR AL EJECUTAR LA CONSULTA\n"+ ex,"E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);      }

            JOptionPane.showMessageDialog(this, "LISTO", "B I E N !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
            }//finde maquinas



            respuesta=JOptionPane.showConfirmDialog(this,"Tranferencia de tintas!!"," I N F O R M A C I O N !!!!!", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                conexioncontrolmaestro();
                rs0=null;
                try{
                    String senSQL="SELECT * FROM Articulos WHERE [Cliente]='"+clavec+"'";
                    rs0=conexion.consulta(senSQL,concontrol);
                    while(rs0.next()){

                        String claveart=rs0.getString("Clave Articulo");
                        Double m2=rs0.getDouble("M2");
                        String t1=""+rs0.getString("1er Color");
                        Double p1=0.0+rs0.getDouble("1er Por");
                        String t2=""+rs0.getString("2o Color");
                        Double p2=0.0+rs0.getDouble("2o Por");
                        String t3=""+rs0.getString("3o Color");
                        Double p3=0.0+rs0.getDouble("3o Por");
                        String t4=""+rs0.getString("4o Color");
                        Double p4=0.0+rs0.getDouble("4o Por");
                        int notintas=0;

                        if(t1.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_tintas(clavearticulo, claveproducto, porcentaje, m2porcentaje) VALUES ('"+claveart+"', '"+t1.toUpperCase()+"', '"+p1+"', '"+(p1*m2)+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                            notintas+=1;
                        }
                        if(t2.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_tintas(clavearticulo, claveproducto, porcentaje, m2porcentaje) VALUES ('"+claveart+"', '"+t2.toUpperCase()+"', '"+p2+"', '"+(p2*m2)+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                            notintas+=1;
                        }
                        if(t3.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_tintas(clavearticulo, claveproducto, porcentaje, m2porcentaje) VALUES ('"+claveart+"', '"+t3.toUpperCase()+"', '"+p3+"', '"+(p3*m2)+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                            notintas+=1;
                        }
                        if(t4.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_tintas(clavearticulo, claveproducto, porcentaje, m2porcentaje) VALUES ('"+claveart+"', '"+t4.toUpperCase()+"', '"+p4+"', '"+(p4*m2)+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                            notintas+=1;
                        }

                        String senSQLt="UPDATE articulos SET tintas='"+notintas+"' WHERE clavearticulo='"+claveart+"';";
                        conexion.modificamov(senSQLt,connj);

                        System.err.println("Articulo:  "+claveart);

                    }
                    if(rs0!=null) {
                        rs0.close();
                    }
                } catch (SQLException ex) {JOptionPane.showMessageDialog(null,"ERROR AL EJECUTAR LA CONSULTA\n"+ ex,"E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);      }

            JOptionPane.showMessageDialog(this, "LISTO", "B I E N !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
            }//finde tintas

            respuesta=JOptionPane.showConfirmDialog(this,"Tranferencia de ARTICULOS!!"," I N F O R M A C I O N !!!!!", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                conexioncontrolmaestro();
                rs0=null;
                try{
                    String senSQL="SELECT * FROM [Articulos Juegos] WHERE [Cliente]='"+clavec+"'";
                    rs0=conexion.consulta(senSQL,concontrol);
                    while(rs0.next()){

                        String claveart=""+rs0.getString("1Articulo");
                        String a2=""+rs0.getString("2Articulo");
                        String a3=""+rs0.getString("3Articulo");
                        String a4=""+rs0.getString("4Articulo");
                        String a5=""+rs0.getString("5Articulo");

                        if(claveart.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_juegos(clavearticulo, clavearticulo1,piezas) VALUES ('"+claveart+"', '"+claveart+"', '"+rs0.getDouble("1Cantidad")+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                        }
                        if(a2.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_juegos(clavearticulo, clavearticulo1,piezas) VALUES ('"+claveart+"', '"+a2+"', '"+rs0.getDouble("2Cantidad")+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                        }
                        if(a3.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_juegos(clavearticulo, clavearticulo1,piezas) VALUES ('"+claveart+"', '"+a3+"', '"+rs0.getDouble("3Cantidad")+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                        }
                        if(a4.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_juegos(clavearticulo, clavearticulo1,piezas) VALUES ('"+claveart+"', '"+a4+"', '"+rs0.getDouble("4Cantidad")+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                        }
                        if(a5.equals("null")){
                        }else{
                            String senSQLmaquina="INSERT INTO articulos_juegos(clavearticulo, clavearticulo1,piezas) VALUES ('"+claveart+"', '"+a5+"', '"+rs0.getDouble("5Cantidad")+"');";
                            conexion.modificamov(senSQLmaquina,connj);
                        }

                        System.err.println("Articulo:  "+claveart);

                    }
                    if(rs0!=null) {
                        rs0.close();
                    }
                } catch (SQLException ex) {JOptionPane.showMessageDialog(null,"ERROR AL EJECUTAR LA CONSULTA\n"+ ex,"E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);      }

            JOptionPane.showMessageDialog(this, "LISTO", "B I E N !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
            }//finde juegos
*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            int respuesta=JOptionPane.showConfirmDialog(this,"Tranferencia de VENTAS ARTICULOS!!"," I N F O R M A C I O N !!!!!", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                conexioncontrolmaestro();
                rs0=null;
                try{
                    String senSQL="SELECT Remisiones.Fecha, Remisiones.[Clave Articulo], Remisiones.Cantidad FROM Remisiones WHERE (((Remisiones.Fecha)>#1/1/2010#)) ORDER BY Remisiones.Fecha;";
                    rs0=conexion.consulta(senSQL,concontrol);
                    while(rs0.next()){
                        String claveart=""+rs0.getString("Clave Articulo");


                        if(claveart.equals("null")){
                        }else{
                            String senSQLmaquina="UPDATE articulos SET fechaultima='"+fechainsertar.format(rs0.getDate("Fecha"))+"', cantidadultima='"+rs0.getInt("Cantidad")+"' WHERE clavearticulo='"+claveart+"';";
                            conexion.modificamov(senSQLmaquina,connj);
                        }

                        System.err.println("Articulo:  "+claveart);

                    }
                    if(rs0!=null) {
                        rs0.close();
                    }
                } catch (Exception ex) {JOptionPane.showMessageDialog(null,"ERROR AL EJECUTAR LA CONSULTA\n"+ ex,"E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);      }

            JOptionPane.showMessageDialog(null, "LISTO", "B I E N !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
            }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
