/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * datos_servidor.java
 *
 * Created on 17/01/2010, 08:56:48 AM
 */

package conta;

import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author IVONNE
 */
public class datos_rutas extends javax.swing.JDialog {
    private Properties conf;

    /** Creates new form datos_servidor */
    public datos_rutas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configuracion();
        //cambia la tecla enter por un tab
        java.util.HashSet conj = new java.util.HashSet(this.getFocusTraversalKeys(java.awt.KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(java.awt.AWTKeyStroke.getAWTKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(java.awt.KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    public void salir(){
        dispose();
        setVisible(false);
    }
    public void configuracion(){
        try{
            conf=conexion.archivoInicial();
            rutaplanos.setText(conf.getProperty("Rutaplanos"));
            rutaxml.setText(conf.getProperty("Rutaxml"));
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this,"No se encuentra archivo de propiedades:\n"+ ex,"E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);  }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rutap = new javax.swing.JFileChooser();
        rutax = new javax.swing.JFileChooser();
        jLabel4 = new javax.swing.JLabel();
        rutaxml = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rutaplanos = new javax.swing.JTextField();
        btnplanos = new javax.swing.JButton();
        btnxml = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(conta.CONTAApp.class).getContext().getResourceMap(datos_rutas.class);
        rutap.setDialogTitle(resourceMap.getString("rutap.dialogTitle")); // NOI18N
        rutap.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        rutap.setName("rutap"); // NOI18N

        rutax.setDialogTitle(resourceMap.getString("rutax.dialogTitle")); // NOI18N
        rutax.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        rutax.setName("rutax"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        rutaxml.setEditable(false);
        rutaxml.setText(resourceMap.getString("rutaxml.text")); // NOI18N
        rutaxml.setFocusable(false);
        rutaxml.setName("rutaxml"); // NOI18N
        rutaxml.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutaxmlFocusGained(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        btnaceptar.setIcon(resourceMap.getIcon("btnaceptar.icon")); // NOI18N
        btnaceptar.setText(resourceMap.getString("btnaceptar.text")); // NOI18N
        btnaceptar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnaceptar.setName("btnaceptar"); // NOI18N
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(resourceMap.getIcon("btncancelar.icon")); // NOI18N
        btncancelar.setText(resourceMap.getString("btncancelar.text")); // NOI18N
        btncancelar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btncancelar.setName("btncancelar"); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        rutaplanos.setEditable(false);
        rutaplanos.setText(resourceMap.getString("rutaplanos.text")); // NOI18N
        rutaplanos.setFocusable(false);
        rutaplanos.setName("rutaplanos"); // NOI18N
        rutaplanos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutaplanosFocusGained(evt);
            }
        });

        btnplanos.setIcon(resourceMap.getIcon("btnplanos.icon")); // NOI18N
        btnplanos.setText(resourceMap.getString("btnplanos.text")); // NOI18N
        btnplanos.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnplanos.setName("btnplanos"); // NOI18N
        btnplanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplanosActionPerformed(evt);
            }
        });

        btnxml.setIcon(resourceMap.getIcon("btnxml.icon")); // NOI18N
        btnxml.setText(resourceMap.getString("btnxml.text")); // NOI18N
        btnxml.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnxml.setName("btnxml"); // NOI18N
        btnxml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rutaxml)
                            .addComponent(rutaplanos, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnplanos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rutaplanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rutaxml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnplanos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxml, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
    if(rutaplanos.getText().equals("") || rutaxml.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "VERIFICA HAY CAMPOS VACIOS", "E R R O R !!!!!!!!!!",JOptionPane.ERROR_MESSAGE);
    }else{
        /**generar archivo*/
        conexion.escribir("Rutaplanos", rutaplanos.getText());
        conexion.escribir("Rutaxml", rutaxml.getText());
        salir();
    }

}//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        salir();
}//GEN-LAST:event_btncancelarActionPerformed

    private void rutaplanosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutaplanosFocusGained
        // TODO add your handling code here:
        rutaplanos.selectAll();
    }//GEN-LAST:event_rutaplanosFocusGained

    private void rutaxmlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutaxmlFocusGained
        // TODO add your handling code here:
        rutaxml.selectAll();
    }//GEN-LAST:event_rutaxmlFocusGained

    private void btnplanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplanosActionPerformed
        // TODO add your handling code here:
        if(rutap.showDialog(this, null)==JFileChooser.APPROVE_OPTION){
            rutaplanos.setText(String.valueOf(rutap.getSelectedFile()));
        }
    }//GEN-LAST:event_btnplanosActionPerformed

    private void btnxmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxmlActionPerformed
        // TODO add your handling code here:
        if(rutax.showDialog(this, null)==JFileChooser.APPROVE_OPTION){
            rutaxml.setText(String.valueOf(rutax.getSelectedFile()));
        }
    }//GEN-LAST:event_btnxmlActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnplanos;
    private javax.swing.JButton btnxml;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFileChooser rutap;
    private javax.swing.JTextField rutaplanos;
    private javax.swing.JFileChooser rutax;
    private javax.swing.JTextField rutaxml;
    // End of variables declaration//GEN-END:variables

}
