/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * temas.java
 *
 * Created on 18/01/2010, 10:04:29 AM
 */

package conta;

import javax.swing.JOptionPane;

/**
 *
 * @author ANGEL
 */
public class temas extends javax.swing.JDialog {

    /** Creates new form temas */
    public temas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public void salir(){
        dispose();
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiutlo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Nebula = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NebulaBrickWall = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        office = new javax.swing.JLabel();
        MistAqua = new javax.swing.JLabel();
        creme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        business = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(conta.CONTAApp.class).getContext().getResourceMap(temas.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        tiutlo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tiutlo.setText(resourceMap.getString("tiutlo.text")); // NOI18N
        tiutlo.setName("tiutlo"); // NOI18N
        tiutlo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiutloMouseClicked(evt);
            }
        });

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel7.foreground")); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        Nebula.setIcon(resourceMap.getIcon("Nebula.icon")); // NOI18N
        Nebula.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Nebula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nebula.setName("Nebula"); // NOI18N
        Nebula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NebulaMouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        NebulaBrickWall.setIcon(resourceMap.getIcon("NebulaBrickWall.icon")); // NOI18N
        NebulaBrickWall.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NebulaBrickWall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NebulaBrickWall.setName("NebulaBrickWall"); // NOI18N
        NebulaBrickWall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NebulaBrickWallMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        office.setIcon(resourceMap.getIcon("office.icon")); // NOI18N
        office.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        office.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        office.setName("office"); // NOI18N
        office.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officeMouseClicked(evt);
            }
        });

        MistAqua.setIcon(resourceMap.getIcon("MistAqua.icon")); // NOI18N
        MistAqua.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MistAqua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MistAqua.setName("MistAqua"); // NOI18N
        MistAqua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MistAquaMouseClicked(evt);
            }
        });

        creme.setIcon(resourceMap.getIcon("creme.icon")); // NOI18N
        creme.setText(resourceMap.getString("creme.text")); // NOI18N
        creme.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        creme.setName("creme"); // NOI18N
        creme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cremeMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        business.setIcon(resourceMap.getIcon("business.icon")); // NOI18N
        business.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        business.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        business.setName("business"); // NOI18N
        business.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businessMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NebulaBrickWall, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creme, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MistAqua, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nebula, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(business, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(business, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nebula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creme, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MistAqua, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NebulaBrickWall, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))))
                .addContainerGap())
        );

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tiutlo, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiutlo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cremeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cremeMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.CremeSkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();

}//GEN-LAST:event_cremeMouseClicked

    private void businessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businessMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.BusinessBlackSteelSkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
}//GEN-LAST:event_businessMouseClicked

    private void officeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officeMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.EnnoviAquaSkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();

}//GEN-LAST:event_officeMouseClicked

    private void NebulaBrickWallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NebulaBrickWallMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.EnnoviPurpleSkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
}//GEN-LAST:event_NebulaBrickWallMouseClicked

    private void MistAquaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MistAquaMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.MistAquaSkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
}//GEN-LAST:event_MistAquaMouseClicked

    private void NebulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NebulaMouseClicked
        // TODO add your handling code here:
        String lf="org.pushingpixels.substance.api.skin.EnnoviGraySkin";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
}//GEN-LAST:event_NebulaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String lf="clasico";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String lf="default";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        String lf="syn";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tiutloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiutloMouseClicked
        // TODO add your handling code here:
        String lf="blueice";
        conexion.escribir("Tema", lf);
        JOptionPane.showMessageDialog(this,"TEMA APLICADOO\nREINICIE EL SISTEMA PARA APLICAR LOS CAMBIOS","G U A R D A D O !!!!!!!!!!",JOptionPane.INFORMATION_MESSAGE);
        salir();
    }//GEN-LAST:event_tiutloMouseClicked

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MistAqua;
    private javax.swing.JLabel Nebula;
    private javax.swing.JLabel NebulaBrickWall;
    private javax.swing.JLabel business;
    private javax.swing.JLabel creme;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel office;
    private javax.swing.JLabel tiutlo;
    // End of variables declaration//GEN-END:variables

}
