/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * visualizar.java
 *
 * Created on 27/05/2010, 05:14:38 PM
 */

package conta;

/**
 *
 * @author ANGEL
 */
public class visualizar extends javax.swing.JDialog {

    /** Creates new form visualizar */
    public visualizar(java.awt.Frame parent, boolean modal,String descripcion,String valor) {
        super(parent, modal);
        initComponents();
        des.setText(descripcion);
        valor1.setText(valor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        des = new javax.swing.JLabel();
        valor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(conta.CONTAApp.class).getContext().getResourceMap(visualizar.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        des.setFont(resourceMap.getFont("des.font")); // NOI18N
        des.setText(resourceMap.getString("des.text")); // NOI18N
        des.setName("des"); // NOI18N

        valor1.setBackground(resourceMap.getColor("valor1.background")); // NOI18N
        valor1.setFont(resourceMap.getFont("valor1.font")); // NOI18N
        valor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor1.setText(resourceMap.getString("valor1.text")); // NOI18N
        valor1.setName("valor1"); // NOI18N
        valor1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(des, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
            .addComponent(valor1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel des;
    private javax.swing.JLabel valor1;
    // End of variables declaration//GEN-END:variables

}
