package com.mx.sit.factura.soap.srv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-10-03T18:35:47.813-05:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://srv.soap.factura.sit.mx.com", name = "cfdiServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface CfdiServiceInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enviaCFDIXMLPDF", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDF")
    @WebMethod(action = "enviaCFDIXMLPDFAction")
    @ResponseWrapper(localName = "enviaCFDIXMLPDFResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDFResponse")
    public boolean enviaCFDIXMLPDF(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "correos", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDF.Correos correos
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelaCFDI", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.CancelaCFDI")
    @WebMethod(action = "cancelaCFDIAction")
    @ResponseWrapper(localName = "cancelaCFDIResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.CancelaCFDIResponse")
    public boolean cancelaCFDI(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validaComprobante", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.ValidaComprobante")
    @WebMethod(action = "validaComprobanteAction")
    @ResponseWrapper(localName = "validaComprobanteResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.ValidaComprobanteResponse")
    public java.lang.String validaComprobante(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "analisis", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        boolean analisis
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraEnviaCFDIXMLPDFTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDFTest")
    @WebMethod(action = "timbraEnviaCFDIXMLPDFTestAction")
    @ResponseWrapper(localName = "timbraEnviaCFDIXMLPDFTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDFTestResponse")
    public boolean timbraEnviaCFDIXMLPDFTest(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "correos", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDFTest.Correos correos
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enviaCFDIXMLPDFTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDFTest")
    @WebMethod(action = "enviaCFDIXMLPDFTestAction")
    @ResponseWrapper(localName = "enviaCFDIXMLPDFTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDFTestResponse")
    public boolean enviaCFDIXMLPDFTest(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "correos", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        com.mx.sit.factura.soap.srv.EnviaCFDIXMLPDFTest.Correos correos
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recuperaCFDIXMLPDF", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLPDF")
    @WebMethod(action = "recuperaCFDIXMLPDFAction")
    @ResponseWrapper(localName = "recuperaCFDIXMLPDFResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLPDFResponse")
    public byte[] recuperaCFDIXMLPDF(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraCFDIXMLPDFTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLPDFTest")
    @WebMethod(action = "timbraCFDIXMLPDFTestAction")
    @ResponseWrapper(localName = "timbraCFDIXMLPDFTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLPDFTestResponse")
    public byte[] timbraCFDIXMLPDFTest(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recuperaCFDIXMLPDFTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLPDFTest")
    @WebMethod(action = "recuperaCFDIXMLPDFTestAction")
    @ResponseWrapper(localName = "recuperaCFDIXMLPDFTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLPDFTestResponse")
    public byte[] recuperaCFDIXMLPDFTest(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraCFDIXML", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXML")
    @WebMethod(action = "timbraCFDIXMLAction")
    @ResponseWrapper(localName = "timbraCFDIXMLResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLResponse")
    public java.lang.String timbraCFDIXML(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recuperaCFDIXML", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXML")
    @WebMethod(action = "recuperaCFDIXMLAction")
    @ResponseWrapper(localName = "recuperaCFDIXMLResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLResponse")
    public java.lang.String recuperaCFDIXML(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelaCFDITest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.CancelaCFDITest")
    @WebMethod(action = "cancelaCFDITestAction")
    @ResponseWrapper(localName = "cancelaCFDITestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.CancelaCFDITestResponse")
    public boolean cancelaCFDITest(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recuperaCFDIXMLTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLTest")
    @WebMethod(action = "recuperaCFDIXMLTestAction")
    @ResponseWrapper(localName = "recuperaCFDIXMLTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.RecuperaCFDIXMLTestResponse")
    public java.lang.String recuperaCFDIXMLTest(
        @WebParam(name = "uuid", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String uuid,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String rfcEmisor,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraEnviaCFDIXMLPDF", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDF")
    @WebMethod(action = "timbraEnviaCFDIXMLPDFAction")
    @ResponseWrapper(localName = "timbraEnviaCFDIXMLPDFResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDFResponse")
    public boolean timbraEnviaCFDIXMLPDF(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "correos", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        com.mx.sit.factura.soap.srv.TimbraEnviaCFDIXMLPDF.Correos correos
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraCFDIXMLPDF", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLPDF")
    @WebMethod(action = "timbraCFDIXMLPDFAction")
    @ResponseWrapper(localName = "timbraCFDIXMLPDFResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLPDFResponse")
    public byte[] timbraCFDIXMLPDF(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validaComprobanteTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.ValidaComprobanteTest")
    @WebMethod(action = "validaComprobanteTestAction")
    @ResponseWrapper(localName = "validaComprobanteTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.ValidaComprobanteTestResponse")
    public java.lang.String validaComprobanteTest(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass,
        @WebParam(name = "analisis", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        boolean analisis
    ) throws FiscoClicException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "timbraCFDIXMLTest", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLTest")
    @WebMethod(action = "timbraCFDIXMLTestAction")
    @ResponseWrapper(localName = "timbraCFDIXMLTestResponse", targetNamespace = "http://srv.soap.factura.sit.mx.com", className = "com.mx.sit.factura.soap.srv.TimbraCFDIXMLTestResponse")
    public java.lang.String timbraCFDIXMLTest(
        @WebParam(name = "cfdi", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String cfdi,
        @WebParam(name = "user", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "http://srv.soap.factura.sit.mx.com")
        java.lang.String pass
    ) throws FiscoClicException_Exception;
}
