
package com.lbs.core.server.timbrado.finkok.registration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "http://facturacion.finkok.com/registration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * This function is in charge of editing an account, it will only be used by the resellers
     * 
     * @param status
     * @param taxpayerId
     * @param resellerPassword
     * @param resellerUsername
     * @return
     *     returns com.lbs.core.server.timbrado.finkok.registration.RegistrationResult
     */
    @WebMethod(action = "edit")
    @WebResult(name = "editResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "edit", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.EditResponse")
    public RegistrationResult edit(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId,
        @WebParam(name = "status", targetNamespace = "http://facturacion.finkok.com/registration")
        String status);

    /**
     * This function is in charge of adding a new user under the reseller, it will only be used by the resellers
     * 
     * @param added
     * @param taxpayerId
     * @param coupon
     * @param resellerPassword
     * @param resellerUsername
     * @return
     *     returns com.lbs.core.server.timbrado.finkok.registration.RegistrationResult
     */
    @WebMethod(action = "add")
    @WebResult(name = "addResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "add", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.AddResponse")
    public RegistrationResult add(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId,
        @WebParam(name = "coupon", targetNamespace = "http://facturacion.finkok.com/registration")
        String coupon,
        @WebParam(name = "added", targetNamespace = "http://facturacion.finkok.com/registration")
        String added);

    /**
     * This function lists all the user of the account if no taxpayer_id is passed otherwise will return the taxpayer_id and status of the given user.
     * 
     * @param taxpayerId
     * @param resellerPassword
     * @param resellerUsername
     * @return
     *     returns com.lbs.core.server.timbrado.finkok.registration.RegistrationListResult
     */
    @WebMethod(action = "get")
    @WebResult(name = "getResult", targetNamespace = "http://facturacion.finkok.com/registration")
    @RequestWrapper(localName = "get", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://facturacion.finkok.com/registration", className = "com.lbs.core.server.timbrado.finkok.registration.GetResponse")
    public RegistrationListResult get(
        @WebParam(name = "reseller_username", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerUsername,
        @WebParam(name = "reseller_password", targetNamespace = "http://facturacion.finkok.com/registration")
        String resellerPassword,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/registration")
        String taxpayerId);

}
